Issue #86: Fix Docker installation
ETP-2927

diff --git a/pipelines/JenkinsFile b/pipelines/JenkinsFile
--- a/pipelines/JenkinsFile
+++ b/pipelines/JenkinsFile
@@ -122,11 +122,16 @@ spec:
           exec:
             command:
               - bash
-              - '-c'
-              - >-
-                chmod a+x /var/run/docker.sock && rm
-                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
-                install -y curl
+              - '-lc'
+              - |
+                set -e
+                chmod a+x /var/run/docker.sock || echo "⚠️ Couldn't chmod docker.sock"
+                rm /etc/apt/sources.list.d/pgdg.list 2>/dev/null || true
+                (apt-get update -y || true)
+                if ! command -v docker >/dev/null 2>&1; then
+                  (apt-get install -y docker.io || echo "⚠️ Couldn't install docker")
+                fi
+                (apt-get install -y curl || echo "⚠️ Couldn't install curl")
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
       imagePullPolicy: IfNotPresent
